# Generated by Django 6.0.6 on 2026-06-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passenger_auth_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='auth_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
