# Generated by Django 4.2.6 on 2026-06-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
