# Generated by Django 6.0.6 on 2026-06-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='auth_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
