# Generated by Django 6.0.6 on 2026-06-06 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('assistance_type', models.CharField(max_length=100)),
                ('additional_note', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.travelrequest')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_reason', models.TextField()),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.helper')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.travelrequest')),
            ],
        ),
    ]
