# Generated by Django 4.2.6 on 2026-06-29 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('travel_request_id', models.UUIDField()),
                ('recommended_helpers', models.JSONField()),
                ('ai_summary', models.TextField()),
                ('model_used', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_recommendations',
                'managed': False,
            },
        ),
    ]
