# Generated by Django 4.2.6 on 2026-06-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('service_type', models.CharField(choices=[('Hospital visit', 'Hospital visit'), ('Govt. office', 'Govt. office'), ('Shopping', 'Shopping'), ('School / Work', 'School / Work'), ('Religious place', 'Religious place'), ('Other', 'Other')], max_length=100)),
                ('assistance_type', models.CharField(choices=[('Wheelchair assistance', 'Wheelchair assistance'), ('Walker support', 'Walker support'), ('Crutches support', 'Crutches support'), ('Walking assistance', 'Walking assistance'), ('Travel companion', 'Travel companion'), ('Hospital visit', 'Hospital visit'), ('Shopping help', 'Shopping help'), ('Govt. office help', 'Govt. office help'), ('Elderly care', 'Elderly care'), ('Visually impaired', 'Visually impaired'), ('Hearing impaired', 'Hearing impaired'), ('Post-surgery', 'Post-surgery')], max_length=100)),
                ('assistance_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='rides.travelrequest')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.helper')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='rides.travelrequest')),
            ],
        ),
    ]
