# Generated by Django 6.0.6 on 2026-06-09 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        ('users', '0003_alter_passenger_auth_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='assistance_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='additional_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='assistance_type',
            field=models.CharField(choices=[('Wheelchair assistance', 'Wheelchair assistance'), ('Walker support', 'Walker support'), ('Crutches support', 'Crutches support'), ('Walking assistance', 'Walking assistance'), ('Travel companion', 'Travel companion'), ('Hospital visit', 'Hospital visit'), ('Shopping help', 'Shopping help'), ('Govt. office help', 'Govt. office help'), ('Elderly care', 'Elderly care'), ('Visually impaired', 'Visually impaired'), ('Hearing impaired', 'Hearing impaired'), ('Post-surgery', 'Post-surgery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='users.passenger'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
