# Generated by Django 4.2.6 on 2026-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecommendation',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchrecommendation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchrecommendation',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
