# Generated by Django 6.0.6 on 2026-06-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_travelrequest_assistance_level_and_more'),
        ('users', '0003_alter_passenger_auth_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='service_type',
            field=models.CharField(choices=[('Hospital visit', 'Hospital visit'), ('Govt. office', 'Govt. office'), ('Shopping', 'Shopping'), ('School / Work', 'School / Work'), ('Religious place', 'Religious place'), ('Other', 'Other')], default='Hospital visit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passenger'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
