# Generated by Django 4.2.6 on 2026-07-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        ('rides', '0002_matchrecommendation_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='assigned_helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='helpers.helper'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
