# Generated by Django 4.2.6 on 2026-07-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_travelrequest_assigned_helper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrecommendation',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='matchrecommendation',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchrecommendation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
