# Generated by Django 4.2.6 on 2026-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_remove_matchrecommendation_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecommendation',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
