# Generated by Django 6.0.6 on 2026-06-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('disability_type', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
