# Generated by Django 6.0.6 on 2026-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='auth_user_id',
            field=models.UUIDField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
