# Generated by Django 6.0.6 on 2026-06-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_passenger_auth_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passenger')),
            ],
        ),
    ]
